module.exports = [
  // Starters (Pre-A1)
  { word: 'apple', phonetic: '/ˈæpəl/', meaning: '苹果', example: 'I eat an apple every day.', exampleCn: '我每天吃一个苹果。', level: 'starters' },
  { word: 'cat', phonetic: '/kæt/', meaning: '猫', example: 'The cat is sleeping.', exampleCn: '猫在睡觉。', level: 'starters' },
  { word: 'dog', phonetic: '/dɒɡ/', meaning: '狗', example: 'My dog likes to play.', exampleCn: '我的狗喜欢玩。', level: 'starters' },
  { word: 'book', phonetic: '/bʊk/', meaning: '书', example: 'This is a good book.', exampleCn: '这是一本好书。', level: 'starters' },
  { word: 'fish', phonetic: '/fɪʃ/', meaning: '鱼', example: 'I can see a fish.', exampleCn: '我能看到一条鱼。', level: 'starters' },
  { word: 'ball', phonetic: '/bɔːl/', meaning: '球', example: 'He kicks the ball.', exampleCn: '他踢球。', level: 'starters' },
  { word: 'sun', phonetic: '/sʌn/', meaning: '太阳', example: 'The sun is hot.', exampleCn: '太阳很热。', level: 'starters' },
  { word: 'milk', phonetic: '/mɪlk/', meaning: '牛奶', example: 'I drink milk in the morning.', exampleCn: '我早上喝牛奶。', level: 'starters' },
  { word: 'bird', phonetic: '/bɜːd/', meaning: '鸟', example: 'A bird is in the tree.', exampleCn: '树上有只鸟。', level: 'starters' },
  { word: 'house', phonetic: '/haʊs/', meaning: '房子', example: 'This is my house.', exampleCn: '这是我的房子。', level: 'starters' },
  { word: 'red', phonetic: '/red/', meaning: '红色', example: 'I like the red car.', exampleCn: '我喜欢那辆红色的车。', level: 'starters' },
  { word: 'blue', phonetic: '/bluː/', meaning: '蓝色', example: 'The sky is blue.', exampleCn: '天空是蓝色的。', level: 'starters' },
  { word: 'tree', phonetic: '/triː/', meaning: '树', example: 'The tree is very tall.', exampleCn: '这棵树很高。', level: 'starters' },
  { word: 'egg', phonetic: '/eɡ/', meaning: '鸡蛋', example: 'I eat an egg for breakfast.', exampleCn: '我早餐吃一个鸡蛋。', level: 'starters' },
  { word: 'cake', phonetic: '/keɪk/', meaning: '蛋糕', example: 'The cake is sweet.', exampleCn: '蛋糕很甜。', level: 'starters' },
  // Movers (A1)
  { word: 'friend', phonetic: '/frend/', meaning: '朋友', example: 'She is my best friend.', exampleCn: '她是我最好的朋友。', level: 'movers' },
  { word: 'school', phonetic: '/skuːl/', meaning: '学校', example: 'I go to school by bus.', exampleCn: '我坐公交车上学。', level: 'movers' },
  { word: 'happy', phonetic: '/ˈhæpi/', meaning: '开心的', example: 'I am very happy today.', exampleCn: '我今天很开心。', level: 'movers' },
  { word: 'water', phonetic: '/ˈwɔːtə/', meaning: '水', example: 'Please give me some water.', exampleCn: '请给我一些水。', level: 'movers' },
  { word: 'family', phonetic: '/ˈfæməli/', meaning: '家庭', example: 'My family has four people.', exampleCn: '我家有四口人。', level: 'movers' },
  { word: 'teacher', phonetic: '/ˈtiːtʃə/', meaning: '老师', example: 'Our teacher is very kind.', exampleCn: '我们的老师很和蔼。', level: 'movers' },
  { word: 'garden', phonetic: '/ˈɡɑːdn/', meaning: '花园', example: 'We play in the garden.', exampleCn: '我们在花园里玩。', level: 'movers' },
  { word: 'library', phonetic: '/ˈlaɪbrəri/', meaning: '图书馆', example: 'I read books in the library.', exampleCn: '我在图书馆看书。', level: 'movers' },
  { word: 'weather', phonetic: '/ˈweðə/', meaning: '天气', example: 'The weather is nice today.', exampleCn: '今天天气很好。', level: 'movers' },
  { word: 'umbrella', phonetic: '/ʌmˈbrelə/', meaning: '雨伞', example: 'Take an umbrella, it may rain.', exampleCn: '带把伞吧，可能会下雨。', level: 'movers' },
  { word: 'breakfast', phonetic: '/ˈbrekfəst/', meaning: '早餐', example: 'I have bread for breakfast.', exampleCn: '我早餐吃面包。', level: 'movers' },
  { word: 'homework', phonetic: '/ˈhəʊmwɜːk/', meaning: '作业', example: 'I finish my homework at night.', exampleCn: '我晚上完成作业。', level: 'movers' },
  { word: 'weekend', phonetic: '/ˌwiːkˈend/', meaning: '周末', example: 'We go to the park on weekend.', exampleCn: '我们周末去公园。', level: 'movers' },
  { word: 'beautiful', phonetic: '/ˈbjuːtɪfl/', meaning: '美丽的', example: 'The flower is beautiful.', exampleCn: '这朵花很美。', level: 'movers' },
  { word: 'crocodile', phonetic: '/ˈkrɒkədaɪl/', meaning: '鳄鱼', example: 'The crocodile has sharp teeth.', exampleCn: '鳄鱼有锋利的牙齿。', level: 'movers' },
  // Flyers (A2)
  { word: 'adventure', phonetic: '/ədˈventʃə/', meaning: '冒险', example: 'The trip was a great adventure.', exampleCn: '这次旅行是一次很棒的冒险。', level: 'flyers' },
  { word: 'machine', phonetic: '/məˈʃiːn/', meaning: '机器', example: 'This machine makes ice cream.', exampleCn: '这台机器制作冰淇淋。', level: 'flyers' },
  { word: 'mountain', phonetic: '/ˈmaʊntən/', meaning: '山', example: 'We climbed the mountain yesterday.', exampleCn: '我们昨天爬山了。', level: 'flyers' },
  { word: 'island', phonetic: '/ˈaɪlənd/', meaning: '岛屿', example: 'They live on a small island.', exampleCn: '他们住在一个小岛上。', level: 'flyers' },
  { word: 'hospital', phonetic: '/ˈhɒspɪtl/', meaning: '医院', example: 'The hospital is near my home.', exampleCn: '医院在我家附近。', level: 'flyers' },
  { word: 'dictionary', phonetic: '/ˈdɪkʃənri/', meaning: '字典', example: 'Use a dictionary to learn new words.', exampleCn: '用字典学习新单词。', level: 'flyers' },
  { word: 'important', phonetic: '/ɪmˈpɔːtnt/', meaning: '重要的', example: 'Exercise is important for health.', exampleCn: '锻炼对健康很重要。', level: 'flyers' },
  { word: 'dangerous', phonetic: '/ˈdeɪndʒərəs/', meaning: '危险的', example: 'It is dangerous to run on the road.', exampleCn: '在马路上跑很危险。', level: 'flyers' },
  { word: 'environment', phonetic: '/ɪnˈvaɪrənmənt/', meaning: '环境', example: 'We should protect the environment.', exampleCn: '我们应该保护环境。', level: 'flyers' },
  { word: 'astronaut', phonetic: '/ˈæstrənɔːt/', meaning: '宇航员', example: 'The astronaut walked in space.', exampleCn: '宇航员在太空中行走。', level: 'flyers' },
  { word: 'volcano', phonetic: '/vɒlˈkeɪnəʊ/', meaning: '火山', example: 'The volcano erupted last year.', exampleCn: '那座火山去年喷发了。', level: 'flyers' },
  { word: 'champion', phonetic: '/ˈtʃæmpiən/', meaning: '冠军', example: 'She is the swimming champion.', exampleCn: '她是游泳冠军。', level: 'flyers' },
  { word: 'thunder', phonetic: '/ˈθʌndə/', meaning: '雷声', example: 'The thunder was very loud.', exampleCn: '雷声很大。', level: 'flyers' },
  { word: 'satellite', phonetic: '/ˈsætəlaɪt/', meaning: '卫星', example: 'The satellite orbits the Earth.', exampleCn: '卫星绕着地球运行。', level: 'flyers' },
  { word: 'treasure', phonetic: '/ˈtreʒə/', meaning: '宝藏', example: 'They found a treasure chest.', exampleCn: '他们找到了一个宝箱。', level: 'flyers' },
  // KET (A2+)
  { word: 'appointment', phonetic: '/əˈpɔɪntmənt/', meaning: '预约', example: 'I have a doctor appointment.', exampleCn: '我预约了医生。', level: 'ket' },
  { word: 'competition', phonetic: '/ˌkɒmpəˈtɪʃn/', meaning: '比赛', example: 'She won the singing competition.', exampleCn: '她赢了歌唱比赛。', level: 'ket' },
  { word: 'experience', phonetic: '/ɪkˈspɪəriəns/', meaning: '经验', example: 'He has a lot of experience.', exampleCn: '他有很多经验。', level: 'ket' },
  { word: 'restaurant', phonetic: '/ˈrestrɒnt/', meaning: '餐厅', example: 'We ate at a nice restaurant.', exampleCn: '我们在一家不错的餐厅吃饭。', level: 'ket' },
  { word: 'suggestion', phonetic: '/səˈdʒestʃən/', meaning: '建议', example: 'Any suggestion for the weekend?', exampleCn: '周末有什么建议吗？', level: 'ket' },
  { word: 'festival', phonetic: '/ˈfestɪvl/', meaning: '节日', example: 'The music festival is in summer.', exampleCn: '音乐节在夏天。', level: 'ket' },
  { word: 'discover', phonetic: '/dɪˈskʌvə/', meaning: '发现', example: 'Scientists discover new things.', exampleCn: '科学家发现新事物。', level: 'ket' },
  { word: 'communicate', phonetic: '/kəˈmjuːnɪkeɪt/', meaning: '交流', example: 'We communicate through emails.', exampleCn: '我们通过邮件交流。', level: 'ket' },
  { word: 'celebrate', phonetic: '/ˈselɪbreɪt/', meaning: '庆祝', example: 'We celebrate birthdays together.', exampleCn: '我们一起庆祝生日。', level: 'ket' },
  { word: 'imagine', phonetic: '/ɪˈmædʒɪn/', meaning: '想象', example: 'Imagine flying in the sky.', exampleCn: '想象在天空中飞翔。', level: 'ket' },
  { word: 'exercise', phonetic: '/ˈeksəsaɪz/', meaning: '锻炼', example: 'Daily exercise keeps you healthy.', exampleCn: '每天锻炼保持健康。', level: 'ket' },
  { word: 'journey', phonetic: '/ˈdʒɜːni/', meaning: '旅程', example: 'The journey takes two hours.', exampleCn: '旅程需要两小时。', level: 'ket' },
  { word: 'knowledge', phonetic: '/ˈnɒlɪdʒ/', meaning: '知识', example: 'Reading gives us knowledge.', exampleCn: '阅读给我们知识。', level: 'ket' },
  { word: 'medicine', phonetic: '/ˈmedsn/', meaning: '药', example: 'Take the medicine after meals.', exampleCn: '饭后吃药。', level: 'ket' },
  { word: 'schedule', phonetic: '/ˈʃedjuːl/', meaning: '时间表', example: 'Check the schedule for tomorrow.', exampleCn: '查看明天的时间表。', level: 'ket' }
]
