module.exports = [
  // === Starters (Pre-A1) — 40 words ===
  { word: 'apple', phonetic: '/ˈæpəl/', meaning: '苹果', example: 'I eat an apple every day.', exampleCn: '我每天吃一个苹果。', level: 'starters' },
  { word: 'cat', phonetic: '/kæt/', meaning: '猫', example: 'The cat is sleeping.', exampleCn: '猫在睡觉。', level: 'starters' },
  { word: 'dog', phonetic: '/dɒɡ/', meaning: '狗', example: 'My dog likes to play.', exampleCn: '我的狗喜欢玩。', level: 'starters' },
  { word: 'book', phonetic: '/bʊk/', meaning: '书', example: 'This is a good book.', exampleCn: '这是一本好书。', level: 'starters' },
  { word: 'fish', phonetic: '/fɪʃ/', meaning: '鱼', example: 'I can see a fish.', exampleCn: '我能看到一条鱼。', level: 'starters' },
  { word: 'ball', phonetic: '/bɔːl/', meaning: '球', example: 'He kicks the ball.', exampleCn: '他踢球。', level: 'starters' },
  { word: 'sun', phonetic: '/sʌn/', meaning: '太阳', example: 'The sun is hot.', exampleCn: '太阳很热。', level: 'starters' },
  { word: 'milk', phonetic: '/mɪlk/', meaning: '牛奶', example: 'I drink milk in the morning.', exampleCn: '我早上喝牛奶。', level: 'starters' },
  { word: 'bird', phonetic: '/bɜːd/', meaning: '鸟', example: 'A bird is in the tree.', exampleCn: '树上有只鸟。', level: 'starters' },
  { word: 'house', phonetic: '/haʊs/', meaning: '房子', example: 'This is my house.', exampleCn: '这是我的房子。', level: 'starters' },
  { word: 'red', phonetic: '/red/', meaning: '红色', example: 'I like the red car.', exampleCn: '我喜欢那辆红色的车。', level: 'starters' },
  { word: 'blue', phonetic: '/bluː/', meaning: '蓝色', example: 'The sky is blue.', exampleCn: '天空是蓝色的。', level: 'starters' },
  { word: 'tree', phonetic: '/triː/', meaning: '树', example: 'The tree is very tall.', exampleCn: '这棵树很高。', level: 'starters' },
  { word: 'egg', phonetic: '/eɡ/', meaning: '鸡蛋', example: 'I eat an egg for breakfast.', exampleCn: '我早餐吃一个鸡蛋。', level: 'starters' },
  { word: 'cake', phonetic: '/keɪk/', meaning: '蛋糕', example: 'The cake is sweet.', exampleCn: '蛋糕很甜。', level: 'starters' },
  { word: 'pen', phonetic: '/pen/', meaning: '钢笔', example: 'I write with a pen.', exampleCn: '我用钢笔写字。', level: 'starters' },
  { word: 'bed', phonetic: '/bed/', meaning: '床', example: 'I go to bed at nine.', exampleCn: '我九点上床睡觉。', level: 'starters' },
  { word: 'car', phonetic: '/kɑː/', meaning: '汽车', example: 'The car is fast.', exampleCn: '汽车很快。', level: 'starters' },
  { word: 'chair', phonetic: '/tʃeə/', meaning: '椅子', example: 'Sit on the chair.', exampleCn: '坐在椅子上。', level: 'starters' },
  { word: 'table', phonetic: '/ˈteɪbl/', meaning: '桌子', example: 'The book is on the table.', exampleCn: '书在桌子上。', level: 'starters' },
  { word: 'water', phonetic: '/ˈwɔːtə/', meaning: '水', example: 'I want some water.', exampleCn: '我想要一些水。', level: 'starters' },
  { word: 'flower', phonetic: '/ˈflaʊə/', meaning: '花', example: 'The flower is beautiful.', exampleCn: '花很美。', level: 'starters' },
  { word: 'star', phonetic: '/stɑː/', meaning: '星星', example: 'I see a star in the sky.', exampleCn: '我看到天上有一颗星。', level: 'starters' },
  { word: 'moon', phonetic: '/muːn/', meaning: '月亮', example: 'The moon is bright tonight.', exampleCn: '今晚月亮很亮。', level: 'starters' },
  { word: 'rain', phonetic: '/reɪn/', meaning: '雨', example: 'The rain is falling.', exampleCn: '正在下雨。', level: 'starters' },
  { word: 'hand', phonetic: '/hænd/', meaning: '手', example: 'Wash your hands.', exampleCn: '洗手。', level: 'starters' },
  { word: 'eye', phonetic: '/aɪ/', meaning: '眼睛', example: 'I have two eyes.', exampleCn: '我有两只眼睛。', level: 'starters' },
  { word: 'nose', phonetic: '/nəʊz/', meaning: '鼻子', example: 'My nose is cold.', exampleCn: '我的鼻子很冷。', level: 'starters' },
  { word: 'mouth', phonetic: '/maʊθ/', meaning: '嘴', example: 'Open your mouth.', exampleCn: '张开嘴。', level: 'starters' },
  { word: 'ear', phonetic: '/ɪə/', meaning: '耳朵', example: 'I hear with my ears.', exampleCn: '我用耳朵听。', level: 'starters' },
  { word: 'shoe', phonetic: '/ʃuː/', meaning: '鞋子', example: 'Put on your shoes.', exampleCn: '穿上鞋子。', level: 'starters' },
  { word: 'hat', phonetic: '/hæt/', meaning: '帽子', example: 'I wear a hat in the sun.', exampleCn: '我在太阳下戴帽子。', level: 'starters' },
  { word: 'shirt', phonetic: '/ʃɜːt/', meaning: '衬衫', example: 'My shirt is white.', exampleCn: '我的衬衫是白色的。', level: 'starters' },
  { word: 'door', phonetic: '/dɔː/', meaning: '门', example: 'Close the door please.', exampleCn: '请关上门。', level: 'starters' },
  { word: 'window', phonetic: '/ˈwɪndəʊ/', meaning: '窗户', example: 'Look out the window.', exampleCn: '看窗外。', level: 'starters' },
  { word: 'boat', phonetic: '/bəʊt/', meaning: '船', example: 'The boat is on the river.', exampleCn: '船在河上。', level: 'starters' },
  { word: 'bus', phonetic: '/bʌs/', meaning: '公交车', example: 'I take the bus to school.', exampleCn: '我坐公交车上学。', level: 'starters' },
  { word: 'clock', phonetic: '/klɒk/', meaning: '时钟', example: 'The clock is on the wall.', exampleCn: '时钟在墙上。', level: 'starters' },
  { word: 'phone', phonetic: '/fəʊn/', meaning: '电话', example: 'The phone is ringing.', exampleCn: '电话在响。', level: 'starters' },
  { word: 'key', phonetic: '/kiː/', meaning: '钥匙', example: 'I lost my key.', exampleCn: '我丢了钥匙。', level: 'starters' },

  // === Movers (A1) — 40 words ===
  { word: 'friend', phonetic: '/frend/', meaning: '朋友', example: 'She is my best friend.', exampleCn: '她是我最好的朋友。', level: 'movers' },
  { word: 'school', phonetic: '/skuːl/', meaning: '学校', example: 'I go to school by bus.', exampleCn: '我坐公交车上学。', level: 'movers' },
  { word: 'happy', phonetic: '/ˈhæpi/', meaning: '开心的', example: 'I am very happy today.', exampleCn: '我今天很开心。', level: 'movers' },
  { word: 'family', phonetic: '/ˈfæməli/', meaning: '家庭', example: 'My family has four people.', exampleCn: '我家有四口人。', level: 'movers' },
  { word: 'teacher', phonetic: '/ˈtiːtʃə/', meaning: '老师', example: 'Our teacher is very kind.', exampleCn: '我们的老师很和蔼。', level: 'movers' },
  { word: 'garden', phonetic: '/ˈɡɑːdn/', meaning: '花园', example: 'We play in the garden.', exampleCn: '我们在花园里玩。', level: 'movers' },
  { word: 'library', phonetic: '/ˈlaɪbrəri/', meaning: '图书馆', example: 'I read books in the library.', exampleCn: '我在图书馆看书。', level: 'movers' },
  { word: 'weather', phonetic: '/ˈweðə/', meaning: '天气', example: 'The weather is nice today.', exampleCn: '今天天气很好。', level: 'movers' },
  { word: 'umbrella', phonetic: '/ʌmˈbrelə/', meaning: '雨伞', example: 'Take an umbrella, it may rain.', exampleCn: '带把伞吧，可能会下雨。', level: 'movers' },
  { word: 'breakfast', phonetic: '/ˈbrekfəst/', meaning: '早餐', example: 'I have bread for breakfast.', exampleCn: '我早餐吃面包。', level: 'movers' },
  { word: 'homework', phonetic: '/ˈhəʊmwɜːk/', meaning: '作业', example: 'I finish my homework at night.', exampleCn: '我晚上完成作业。', level: 'movers' },
  { word: 'weekend', phonetic: '/ˌwiːkˈend/', meaning: '周末', example: 'We go to the park on weekend.', exampleCn: '我们周末去公园。', level: 'movers' },
  { word: 'beautiful', phonetic: '/ˈbjuːtɪfl/', meaning: '美丽的', example: 'The flower is beautiful.', exampleCn: '这朵花很美。', level: 'movers' },
  { word: 'crocodile', phonetic: '/ˈkrɒkədaɪl/', meaning: '鳄鱼', example: 'The crocodile has sharp teeth.', exampleCn: '鳄鱼有锋利的牙齿。', level: 'movers' },
  { word: 'animal', phonetic: '/ˈænɪml/', meaning: '动物', example: 'I love animals.', exampleCn: '我喜欢动物。', level: 'movers' },
  { word: 'classroom', phonetic: '/ˈklɑːsruːm/', meaning: '教室', example: 'Our classroom is big.', exampleCn: '我们的教室很大。', level: 'movers' },
  { word: 'pencil', phonetic: '/ˈpensl/', meaning: '铅笔', example: 'I write with a pencil.', exampleCn: '我用铅笔写字。', level: 'movers' },
  { word: 'picture', phonetic: '/ˈpɪktʃə/', meaning: '图片', example: 'I draw a picture.', exampleCn: '我画了一幅画。', level: 'movers' },
  { word: 'music', phonetic: '/ˈmjuːzɪk/', meaning: '音乐', example: 'I like listening to music.', exampleCn: '我喜欢听音乐。', level: 'movers' },
  { word: 'story', phonetic: '/ˈstɔːri/', meaning: '故事', example: 'Tell me a story.', exampleCn: '给我讲个故事。', level: 'movers' },
  { word: 'river', phonetic: '/ˈrɪvə/', meaning: '河', example: 'The river is long.', exampleCn: '这条河很长。', level: 'movers' },
  { word: 'forest', phonetic: '/ˈfɒrɪst/', meaning: '森林', example: 'The forest is dark.', exampleCn: '森林很暗。', level: 'movers' },
  { word: 'bicycle', phonetic: '/ˈbaɪsɪkl/', meaning: '自行车', example: 'I ride my bicycle to school.', exampleCn: '我骑自行车上学。', level: 'movers' },
  { word: 'airport', phonetic: '/ˈeəpɔːt/', meaning: '机场', example: 'We meet at the airport.', exampleCn: '我们在机场见面。', level: 'movers' },
  { word: 'sandwich', phonetic: '/ˈsænwɪtʃ/', meaning: '三明治', example: 'I eat a sandwich for lunch.', exampleCn: '我午餐吃三明治。', level: 'movers' },
  { word: 'banana', phonetic: '/bəˈnɑːnə/', meaning: '香蕉', example: 'The monkey eats a banana.', exampleCn: '猴子吃香蕉。', level: 'movers' },
  { word: 'orange', phonetic: '/ˈɒrɪndʒ/', meaning: '橙子', example: 'The orange is sweet.', exampleCn: '橙子很甜。', level: 'movers' },
  { word: 'doctor', phonetic: '/ˈdɒktə/', meaning: '医生', example: 'The doctor helps sick people.', exampleCn: '医生帮助病人。', level: 'movers' },
  { word: 'police', phonetic: '/pəˈliːs/', meaning: '警察', example: 'The police catch bad people.', exampleCn: '警察抓坏人。', level: 'movers' },
  { word: 'kitchen', phonetic: '/ˈkɪtʃɪn/', meaning: '厨房', example: 'Mom cooks in the kitchen.', exampleCn: '妈妈在厨房做饭。', level: 'movers' },
  { word: 'bedroom', phonetic: '/ˈbedruːm/', meaning: '卧室', example: 'My bedroom is small.', exampleCn: '我的卧室很小。', level: 'movers' },
  { word: 'summer', phonetic: '/ˈsʌmə/', meaning: '夏天', example: 'I swim in summer.', exampleCn: '我夏天游泳。', level: 'movers' },
  { word: 'winter', phonetic: '/ˈwɪntə/', meaning: '冬天', example: 'It snows in winter.', exampleCn: '冬天下雪。', level: 'movers' },
  { word: 'spring', phonetic: '/sprɪŋ/', meaning: '春天', example: 'Flowers grow in spring.', exampleCn: '春天花朵生长。', level: 'movers' },
  { word: 'autumn', phonetic: '/ˈɔːtəm/', meaning: '秋天', example: 'Leaves fall in autumn.', exampleCn: '秋天树叶落下。', level: 'movers' },
  { word: 'cloud', phonetic: '/klaʊd/', meaning: '云', example: 'The cloud looks like a sheep.', exampleCn: '那朵云像一只羊。', level: 'movers' },
  { word: 'wind', phonetic: '/wɪnd/', meaning: '风', example: 'The wind is strong today.', exampleCn: '今天风很大。', level: 'movers' },
  { word: 'snow', phonetic: '/snəʊ/', meaning: '雪', example: 'The snow is white.', exampleCn: '雪是白色的。', level: 'movers' },
  { word: 'horse', phonetic: '/hɔːs/', meaning: '马', example: 'The horse runs fast.', exampleCn: '马跑得很快。', level: 'movers' },
  { word: 'rabbit', phonetic: '/ˈræbɪt/', meaning: '兔子', example: 'The rabbit has long ears.', exampleCn: '兔子有长耳朵。', level: 'movers' },
  { word: 'elephant', phonetic: '/ˈelɪfənt/', meaning: '大象', example: 'The elephant is very big.', exampleCn: '大象很大。', level: 'movers' },

  // === Flyers (A2) — 40 words ===
  { word: 'adventure', phonetic: '/ədˈventʃə/', meaning: '冒险', example: 'The trip was a great adventure.', exampleCn: '这次旅行是一次很棒的冒险。', level: 'flyers' },
  { word: 'machine', phonetic: '/məˈʃiːn/', meaning: '机器', example: 'This machine makes ice cream.', exampleCn: '这台机器制作冰淇淋。', level: 'flyers' },
  { word: 'mountain', phonetic: '/ˈmaʊntən/', meaning: '山', example: 'We climbed the mountain yesterday.', exampleCn: '我们昨天爬山了。', level: 'flyers' },
  { word: 'island', phonetic: '/ˈaɪlənd/', meaning: '岛屿', example: 'They live on a small island.', exampleCn: '他们住在一个小岛上。', level: 'flyers' },
  { word: 'hospital', phonetic: '/ˈhɒspɪtl/', meaning: '医院', example: 'The hospital is near my home.', exampleCn: '医院在我家附近。', level: 'flyers' },
  { word: 'dictionary', phonetic: '/ˈdɪkʃənri/', meaning: '字典', example: 'Use a dictionary to learn new words.', exampleCn: '用字典学习新单词。', level: 'flyers' },
  { word: 'important', phonetic: '/ɪmˈpɔːtnt/', meaning: '重要的', example: 'Exercise is important for health.', exampleCn: '锻炼对健康很重要。', level: 'flyers' },
  { word: 'dangerous', phonetic: '/ˈdeɪndʒərəs/', meaning: '危险的', example: 'It is dangerous to run on the road.', exampleCn: '在马路上跑很危险。', level: 'flyers' },
  { word: 'environment', phonetic: '/ɪnˈvaɪrənmənt/', meaning: '环境', example: 'We should protect the environment.', exampleCn: '我们应该保护环境。', level: 'flyers' },
  { word: 'astronaut', phonetic: '/ˈæstrənɔːt/', meaning: '宇航员', example: 'The astronaut walked in space.', exampleCn: '宇航员在太空中行走。', level: 'flyers' },
  { word: 'volcano', phonetic: '/vɒlˈkeɪnəʊ/', meaning: '火山', example: 'The volcano erupted last year.', exampleCn: '那座火山去年喷发了。', level: 'flyers' },
  { word: 'champion', phonetic: '/ˈtʃæmpiən/', meaning: '冠军', example: 'She is the swimming champion.', exampleCn: '她是游泳冠军。', level: 'flyers' },
  { word: 'thunder', phonetic: '/ˈθʌndə/', meaning: '雷声', example: 'The thunder was very loud.', exampleCn: '雷声很大。', level: 'flyers' },
  { word: 'satellite', phonetic: '/ˈsætəlaɪt/', meaning: '卫星', example: 'The satellite orbits the Earth.', exampleCn: '卫星绕着地球运行。', level: 'flyers' },
  { word: 'treasure', phonetic: '/ˈtreʒə/', meaning: '宝藏', example: 'They found a treasure chest.', exampleCn: '他们找到了一个宝箱。', level: 'flyers' },
  { word: 'umbrella', phonetic: '/ʌmˈbrelə/', meaning: '雨伞', example: 'Take an umbrella, it may rain.', exampleCn: '带把伞吧，可能会下雨。', level: 'flyers' },
  { word: 'cinema', phonetic: '/ˈsɪnəmə/', meaning: '电影院', example: 'We watch movies at the cinema.', exampleCn: '我们在电影院看电影。', level: 'flyers' },
  { word: 'concert', phonetic: '/ˈkɒnsət/', meaning: '音乐会', example: 'The concert was amazing.', exampleCn: '音乐会很精彩。', level: 'flyers' },
  { word: 'museum', phonetic: '/mjuˈziːəm/', meaning: '博物馆', example: 'The museum has dinosaur bones.', exampleCn: '博物馆有恐龙骨架。', level: 'flyers' },
  { word: 'passport', phonetic: '/ˈpɑːspɔːt/', meaning: '护照', example: 'You need a passport to travel abroad.', exampleCn: '出国旅行需要护照。', level: 'flyers' },
  { word: 'suitcase', phonetic: '/ˈsuːtkeɪs/', meaning: '行李箱', example: 'I packed my suitcase for the trip.', exampleCn: '我为旅行整理了行李箱。', level: 'flyers' },
  { word: 'mechanic', phonetic: '/məˈkænɪk/', meaning: '机械师', example: 'The mechanic fixed my car.', exampleCn: '机械师修好了我的车。', level: 'flyers' },
  { word: 'scientist', phonetic: '/ˈsaɪəntɪst/', meaning: '科学家', example: 'The scientist discovered a new star.', exampleCn: '科学家发现了一颗新星。', level: 'flyers' },
  { word: 'explorer', phonetic: '/ɪkˈsplɔːrə/', meaning: '探险家', example: 'The explorer found a new cave.', exampleCn: '探险家发现了一个新洞穴。', level: 'flyers' },
  { word: 'computer', phonetic: '/kəmˈpjuːtə/', meaning: '电脑', example: 'I use a computer to learn.', exampleCn: '我用电脑学习。', level: 'flyers' },
  { word: 'internet', phonetic: '/ˈɪntənet/', meaning: '互联网', example: 'We can find information on the internet.', exampleCn: '我们可以在互联网上找到信息。', level: 'flyers' },
  { word: 'program', phonetic: '/ˈprəʊɡræm/', meaning: '程序', example: 'I wrote a simple program.', exampleCn: '我写了一个简单的程序。', level: 'flyers' },
  { word: 'robot', phonetic: '/ˈrəʊbɒt/', meaning: '机器人', example: 'The robot can walk and talk.', exampleCn: '机器人会走路和说话。', level: 'flyers' },
  { word: 'energy', phonetic: '/ˈenədʒi/', meaning: '能源', example: 'Solar energy is clean.', exampleCn: '太阳能是清洁能源。', level: 'flyers' },
  { word: 'experiment', phonetic: '/ɪkˈsperɪmənt/', meaning: '实验', example: 'We did a science experiment.', exampleCn: '我们做了一个科学实验。', level: 'flyers' },
  { word: 'invention', phonetic: '/ɪnˈvenʃn/', meaning: '发明', example: 'The phone is a great invention.', exampleCn: '电话是一项伟大的发明。', level: 'flyers' },
  { word: 'temperature', phonetic: '/ˈtemprətʃə/', meaning: '温度', example: 'The temperature is 25 degrees.', exampleCn: '温度是25度。', level: 'flyers' },
  { word: 'degree', phonetic: '/dɪˈɡriː/', meaning: '度数', example: 'Water boils at 100 degrees.', exampleCn: '水在100度沸腾。', level: 'flyers' },
  { word: 'graduate', phonetic: '/ˈɡrædʒueɪt/', meaning: '毕业', example: 'She will graduate next year.', exampleCn: '她明年毕业。', level: 'flyers' },
  { word: 'uniform', phonetic: '/ˈjuːnɪfɔːm/', meaning: '制服', example: 'Students wear uniforms at school.', exampleCn: '学生在学校穿制服。', level: 'flyers' },
  { word: 'exhibition', phonetic: '/ˌeksɪˈbɪʃn/', meaning: '展览', example: 'We visited an art exhibition.', exampleCn: '我们参观了一个艺术展。', level: 'flyers' },
  { word: 'passenger', phonetic: '/ˈpæsɪndʒə/', meaning: '乘客', example: 'The passengers waited for the train.', exampleCn: '乘客们等待火车。', level: 'flyers' },
  { word: 'luggage', phonetic: '/ˈlʌɡɪdʒ/', meaning: '行李', example: 'My luggage is very heavy.', exampleCn: '我的行李很重。', level: 'flyers' },
  { word: 'receipt', phonetic: '/rɪˈsiːt/', meaning: '收据', example: 'Keep the receipt please.', exampleCn: '请保留收据。', level: 'flyers' },
  { word: 'scissors', phonetic: '/ˈsɪzəz/', meaning: '剪刀', example: 'I use scissors to cut paper.', exampleCn: '我用剪刀剪纸。', level: 'flyers' },
  { word: 'envelope', phonetic: '/ˈenvələʊp/', meaning: '信封', example: 'Put the letter in the envelope.', exampleCn: '把信放进信封里。', level: 'flyers' },

  // === KET (A2+) — 40 words ===
  { word: 'appointment', phonetic: '/əˈpɔɪntmənt/', meaning: '预约', example: 'I have a doctor appointment.', exampleCn: '我预约了医生。', level: 'ket' },
  { word: 'competition', phonetic: '/ˌkɒmpəˈtɪʃn/', meaning: '比赛', example: 'She won the singing competition.', exampleCn: '她赢了歌唱比赛。', level: 'ket' },
  { word: 'experience', phonetic: '/ɪkˈspɪəriəns/', meaning: '经验', example: 'He has a lot of experience.', exampleCn: '他有很多经验。', level: 'ket' },
  { word: 'restaurant', phonetic: '/ˈrestrɒnt/', meaning: '餐厅', example: 'We ate at a nice restaurant.', exampleCn: '我们在一家不错的餐厅吃饭。', level: 'ket' },
  { word: 'suggestion', phonetic: '/səˈdʒestʃən/', meaning: '建议', example: 'Any suggestion for the weekend?', exampleCn: '周末有什么建议吗？', level: 'ket' },
  { word: 'festival', phonetic: '/ˈfestɪvl/', meaning: '节日', example: 'The music festival is in summer.', exampleCn: '音乐节在夏天。', level: 'ket' },
  { word: 'discover', phonetic: '/dɪˈskʌvə/', meaning: '发现', example: 'Scientists discover new things.', exampleCn: '科学家发现新事物。', level: 'ket' },
  { word: 'communicate', phonetic: '/kəˈmjuːnɪkeɪt/', meaning: '交流', example: 'We communicate through emails.', exampleCn: '我们通过邮件交流。', level: 'ket' },
  { word: 'celebrate', phonetic: '/ˈselɪbreɪt/', meaning: '庆祝', example: 'We celebrate birthdays together.', exampleCn: '我们一起庆祝生日。', level: 'ket' },
  { word: 'imagine', phonetic: '/ɪˈmædʒɪn/', meaning: '想象', example: 'Imagine flying in the sky.', exampleCn: '想象在天空中飞翔。', level: 'ket' },
  { word: 'exercise', phonetic: '/ˈeksəsaɪz/', meaning: '锻炼', example: 'Daily exercise keeps you healthy.', exampleCn: '每天锻炼保持健康。', level: 'ket' },
  { word: 'journey', phonetic: '/ˈdʒɜːni/', meaning: '旅程', example: 'The journey takes two hours.', exampleCn: '旅程需要两小时。', level: 'ket' },
  { word: 'knowledge', phonetic: '/ˈnɒlɪdʒ/', meaning: '知识', example: 'Reading gives us knowledge.', exampleCn: '阅读给我们知识。', level: 'ket' },
  { word: 'medicine', phonetic: '/ˈmedsn/', meaning: '药', example: 'Take the medicine after meals.', exampleCn: '饭后吃药。', level: 'ket' },
  { word: 'schedule', phonetic: '/ˈʃedjuːl/', meaning: '时间表', example: 'Check the schedule for tomorrow.', exampleCn: '查看明天的时间表。', level: 'ket' },
  { word: 'advantage', phonetic: '/ədˈvɑːntɪdʒ/', meaning: '优势', example: 'Speaking English is an advantage.', exampleCn: '会说英语是一种优势。', level: 'ket' },
  { word: 'available', phonetic: '/əˈveɪləbl/', meaning: '可用的', example: 'The book is available in the library.', exampleCn: '这本书图书馆有。', level: 'ket' },
  { word: 'comfortable', phonetic: '/ˈkʌmftəbl/', meaning: '舒适的', example: 'This chair is very comfortable.', exampleCn: '这把椅子很舒服。', level: 'ket' },
  { word: 'consider', phonetic: '/kənˈsɪdə/', meaning: '考虑', example: 'I will consider your offer.', exampleCn: '我会考虑你的提议。', level: 'ket' },
  { word: 'decision', phonetic: '/dɪˈsɪʒn/', meaning: '决定', example: 'It was a difficult decision.', exampleCn: '这是一个艰难的决定。', level: 'ket' },
  { word: 'difficulty', phonetic: '/ˈdɪfɪkəlti/', meaning: '困难', example: 'I have difficulty with math.', exampleCn: '我数学有困难。', level: 'ket' },
  { word: 'education', phonetic: '/ˌedʒuˈkeɪʃn/', meaning: '教育', example: 'Education is important for everyone.', exampleCn: '教育对每个人都很重要。', level: 'ket' },
  { word: 'emergency', phonetic: '/iˈmɜːdʒənsi/', meaning: '紧急情况', example: 'Call 120 in an emergency.', exampleCn: '紧急情况拨打120。', level: 'ket' },
  { word: 'expensive', phonetic: '/ɪkˈspensɪv/', meaning: '昂贵的', example: 'The watch is very expensive.', exampleCn: '这块表很贵。', level: 'ket' },
  { word: 'favourite', phonetic: '/ˈfeɪvərɪt/', meaning: '最喜欢的', example: 'Blue is my favourite colour.', exampleCn: '蓝色是我最喜欢的颜色。', level: 'ket' },
  { word: 'forecast', phonetic: '/ˈfɔːkɑːst/', meaning: '预报', example: 'The weather forecast says it will rain.', exampleCn: '天气预报说会下雨。', level: 'ket' },
  { word: 'gradually', phonetic: '/ˈɡrædʒuəli/', meaning: '逐渐地', example: 'The weather gradually got warmer.', exampleCn: '天气逐渐变暖。', level: 'ket' },
  { word: 'guarantee', phonetic: '/ˌɡærənˈtiː/', meaning: '保证', example: 'I guarantee you will love it.', exampleCn: '我保证你会喜欢。', level: 'ket' },
  { word: 'hesitate', phonetic: '/ˈhezɪteɪt/', meaning: '犹豫', example: 'Do not hesitate to ask questions.', exampleCn: '不要犹豫，尽管问。', level: 'ket' },
  { word: 'improve', phonetic: '/ɪmˈpruːv/', meaning: '改善', example: 'I want to improve my English.', exampleCn: '我想提高我的英语。', level: 'ket' },
  { word: 'interest', phonetic: '/ˈɪntrəst/', meaning: '兴趣', example: 'I have an interest in science.', exampleCn: '我对科学感兴趣。', level: 'ket' },
  { word: 'lecture', phonetic: '/ˈlektʃə/', meaning: '讲座', example: 'The professor gave a great lecture.', exampleCn: '教授做了一个精彩的讲座。', level: 'ket' },
  { word: 'memory', phonetic: '/ˈmeməri/', meaning: '记忆', example: 'I have a good memory.', exampleCn: '我记忆力很好。', level: 'ket' },
  { word: 'necessary', phonetic: '/ˈnesəsəri/', meaning: '必要的', example: 'Sleep is necessary for health.', exampleCn: '睡眠对健康是必要的。', level: 'ket' },
  { word: 'opinion', phonetic: '/əˈpɪnjən/', meaning: '观点', example: 'In my opinion, this is the best.', exampleCn: '在我看来，这是最好的。', level: 'ket' },
  { word: 'popular', phonetic: '/ˈpɒpjələ/', meaning: '受欢迎的', example: 'This song is very popular.', exampleCn: '这首歌很受欢迎。', level: 'ket' },
  { word: 'recognize', phonetic: '/ˈrekəɡnaɪz/', meaning: '认出', example: 'I did not recognize her at first.', exampleCn: '我一开始没认出她。', level: 'ket' },
  { word: 'seriously', phonetic: '/ˈsɪəriəsli/', meaning: '认真地', example: 'Take your studies seriously.', exampleCn: '认真学习。', level: 'ket' },
  { word: 'technique', phonetic: '/tekˈniːk/', meaning: '技术', example: 'She learned a new painting technique.', exampleCn: '她学了一种新的绘画技法。', level: 'ket' },
  { word: 'volunteer', phonetic: '/ˌvɒlənˈtɪə/', meaning: '志愿者', example: 'He works as a volunteer on weekends.', exampleCn: '他周末做志愿者。', level: 'ket' },
  { word: 'warning', phonetic: '/ˈwɔːnɪŋ/', meaning: '警告', example: 'The sign is a warning.', exampleCn: '那个标志是一个警告。', level: 'ket' }
]
